spring:
  data:
    mongodb:
      database: people
links:
  cats: "https://api.thecatapi.com/v1/breeds"
  countries: "https://restcountries.com/v3.1/all"
  #    name: "https://restcountries.com/v3.1/name/"
  cities: "https://restcountries.com/v3.1/capital/{capital}"
  persons: "https://gorest.co.in/public/v1/users"
  cars: "https://the-vehicles-api.herokuapp.com/brands/"
  random_user: "https://randomuser.me/api"
MAPS_API_KEY: ""

---

spring:
  config:
    activate:
      on-profile: cloud